SunshareHub/Models/LeadViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace SunshareHub.Models
{
    public class LeadViewModel
    {
        [Required]
        [DisplayName("First name")]
        public string FirstName { get; set; }
        [Required]
        [DisplayName("Last name")]
        public string LastName { get; set; }
        [DisplayName("Service Address")]
        public string ServiceAddress { get;set; }
        public int Phone { get; set; }
        public IQueryable<SelectListItem> States { get; set; }
        [DisplayName("State")]
        public int StateId { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        [DisplayName("Zip Code")]
        public int ZipCode { get; set; }
        [DisplayName("Contract Status")]
        public int LeadStausId { get; set; }
        public string Email { get; set; }
        public IQueryable<SelectListItem> Subscriptions { get; set; }
        public string Subscription { get; set; }
        [DisplayName("Utility Account Number")]
        public string UtilityAccountNumber { get; set; }
        [DisplayName("Utility Provider")]
        public string UtilityProvider { get; set; }
        public IQueryable<SelectListItem> Campaigns { get; set; }
        [DisplayName("Campaign")]
        public int CampaignId { get; set; }
        [DisplayName("Refered By")]
        public string ReferedBy { get; set; }
        public IQueryable<SelectListItem> LeadSources { get; set; }
        [DisplayName("Lead Source")]
        public int LeadSourceId { get; set; }
        public int SalesRepId { get; set; }
        [DisplayName("Date Of Birth")]
        public DateTime DateOfBirth { get; set; }
    }
}

SunshareHub/Controllers/LeadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SunshareDatabase;
using SunshareHub.ModelAssembler;
using SunshareHub.Models;

namespace SunshareHub.Controllers
{
    public class LeadController : Controller
    {
        private static readonly SunshareDatabaseContext Context = new SunshareDatabaseContext();
        readonly LeadViewModelAssembler _assembler = new LeadViewModelAssembler(Context);
        // GET: Lead
        public ActionResult Index()
        {
            return View(_assembler.Assemble(6));
        }

        public ActionResult Save(LeadViewModel model)
        {
            return View("~/Views/Dashboard/Dashboard.cshtml");
        }
    }
}

SunshareHub/Views/Lead/Index.cshtml
@model SunshareHub.Models.LeadViewModel

<!DOCTYPE html>
@using (Html.BeginForm("Save", "Lead", FormMethod.Post,
    new {enctype = "multipart/form-data"}))
{
    <div class="row">
    <div class="col-md-6">
    <div class="hpanel">
    <div class="panel-heading hbuilt-primary"> Personal Information </div>
    <div class="panel-body">
    <div class="row">
    <div class="col-lg-6 animated-panel zoomIn" style="animation-delay: 0.3s;">
        <div class="form-group">
            @Html.LabelFor(m => m.FirstName)
            @Html.TextBoxFor(m => m.FirstName, new {@class = "form-control"})
        </div>
        <div class="form-group">
            @Html.LabelFor(m=>m.ServiceAddress)
            @Html.TextAreaFor(m=>m.ServiceAddress,new {@class="form-control" ,@id="address"})
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.City)
            @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ZipCode)
            @Html.TextBoxFor(m => m.ZipCode, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Email)
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="col-lg-6  animated-panel zoomIn" style="animation-delay: 0.4s;">
        <div class="form-group">
            @Html.LabelFor(m => m.LastName)
            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>Apt No</label>
            <textarea tabindex="3" maxlength="25" rows="3" name="address" class="form-control"></textarea>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.StateId)
            @Html.DropDownListFor(m => m.StateId,Model.States, new { @class = "form-control" , @Id="state"})
        </div>
        <div class="form-group">
            <label>County <span style="color: red;">*</span></label>
            <select tabindex="8" id="country" name="country" class="form-control">
                <option value="0">-- Select County --</option>
            </select>
            <span style="color: red" id="countryerr"></span>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Phone)
            @Html.TextBoxFor(m => m.Phone, new { @class = "form-control" })
        </div>
    </div>
    <div class="col-md-12 ">
        <div class="form-body">
            <div class="form-group">
                @Html.LabelFor(m => m.DateOfBirth)
                @Html.TextBoxFor(m => m.DateOfBirth, new { @class = "form-control datepicker" })
            </div>
        </div>
    </div>
    </div>
    </div>
    </div>
    <div class="hpanel">
        <div class="panel-heading hbuilt-primary">Utility Info</div>
        <div class="panel-body">
            <div class="form-group">
                <div class="row">
                    <div class="col-md-3">
                        <label>Subscription %: </label>
                    </div>
                    <div class="col-md-3">
                        <label class="radio-inline">
                            <div class="radio">
                                <input type="radio" tabindex="15" id="suboption2" name="suboption" value="80">
                            </div>
                            80%
                        </label>
                    </div>
                    <div class="col-md-3">
                        <label class="radio-inline">
                            <div class="radio">
                                <input type="radio" checked="" tabindex="16" id="suboption2" name="suboption" value="100">
                            </div>
                            100%
                        </label>
                    </div>
                    <div style="width: 20%" class="col-md-2">
                        <label class="radio-inline">
                            <div class="radio">
                                <input type="radio" tabindex="17" id="suboption3" name="suboption" value="120">
                            </div>
                            120%
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group m-t-10">
                <div class="row">
                    <div class="col-md-6">
                        <label>Utility Account number</label>
                        <input type="textbox" maxlength="30" tabindex="18" placeholder="" class="form-control" id="uan" name="uan">
                    </div>
                    <div class="col-md-6">
                        <label>Utility provider</label>
                        <input type="textbox" tabindex="19" readonly value="Xcel Energy Provider" class="form-control" id="upn" name="upn">
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="col-md-6">
        <div class="hpanel">
            <div class="panel-body">
                <div class="row">
                    <div style="margin-top: 8px;" class="col-md-2"><span class="label label-default" id="status_notsent"><i class="fa fa-fw fa-check-circle"></i>Not Sent</span></div>
                    <div style="margin-top: 8px;" class="col-md-2"><span id="status_delivered" class="label label-default"><i class="fa fa-fw fa-check-circle"></i>Delivered</span></div>
                    <div style="margin-top: 8px;" class="col-md-2"><span id="status_declined" class="label label-default"><i class="fa fa-fw fa-check-circle"></i>Declined</span></div>
                    <div style="margin-top: 8px;" class="col-md-2"><span id="status_signed" class="label label-default"><i class="fa fa-fw fa-check-circle"></i>Signed</span></div>
                    <div class="col-md-4"><button name="checkstatus" id="checkstatus" class="btn btn-info btn-block" type="button">Check Status</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="hpanel">
            <div class="panel-heading hbuilt-primary"> User Preference </div>
            <div class="panel-body">
                <div class="form-group">
                    <label>Campaign:<span style="color: red;">*</span></label>
                    <select class="form-control" name="state" placeholder="Select State" tabindex="6">
                        <option value="0">-- Select Campaign --</option>
                        <option value="Minnesota">$200 Restaurant.com</option>
                        <option value="Colorado">$50 Visa</option>
                        <option value="Colorado">$50 Visa</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="control-label">Referred by </label>
                    <input type="text" class="form-control">
                </div>
            </div>
        </div>
        <div class="hpanel">
            <div class="panel-heading hbuilt-primary"> WHAT MADE YOU CALL US TODAY?* </div>
            <div class="panel-body">
                <div class="form-group">
                    <label>Campaign:<span style="color: red;">*</span></label>
                    <select class="form-control" name="state" placeholder="Select State" tabindex="6">
                        <option value="0">-- Select Campaign --</option>
                        <option value="Minnesota">Educational Mailer </option>
                        <option value="Colorado">Rate Hike Mailer</option>
                        <option value="Colorado">Incentive Mailer</option>
                        <option value="Minnesota"> Radio</option>
                        <option value="Colorado">Newspaper</option>
                        <option value="Colorado"> Online Video</option>
                        <option value="Minnesota">Online advertising: no offer</option>
                        <option value="Colorado">Outbound Call</option>
                        <option value="Colorado"> Billboard</option>
                        <option value="Minnesota">Facebook </option>
                        <option value="Colorado"> Twitter </option>
                        <option value="Colorado">Referral </option>
                        <option value="Minnesota">Web Search </option>
                        <option value="Colorado"> Other </option>
                        <option value="Colorado"> Online advertising: with $200 restaurant.com offer </option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    </div>
    <!-- Right sidebar -->
    <div id="right-sidebar" class="animated fadeInRight">
        <div class="p-m">
            <button id="sidebar-close" class="right-sidebar-toggle sidebar-button btn btn-default m-b-md"><i class="pe pe-7s-close"></i> </button>
            <div>
                <span class="font-bold no-margins"> Analytics </span> <br>
                <small> Lorem Ipsum is simply dummy text of the printing simply all dummy text.</small>
            </div>
            <div class="row m-t-sm m-b-sm">
                <div class="col-lg-6">
                    <h3 class="no-margins font-extra-bold text-success">300,102</h3>
                    <div class="font-bold">98% <i class="fa fa-level-up text-success"></i>
                    </div>
                </div>
                <div class="col-lg-6">
                    <h3 class="no-margins font-extra-bold text-success">280,200</h3>
                    <div class="font-bold">98% <i class="fa fa-level-up text-success"></i>
                    </div>
                </div>
            </div>
            <div class="progress m-t-xs full progress-small">
                <div style="width: 25%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="25" role="progressbar"
                     class=" progress-bar progress-bar-success"><span class="sr-only">35% Complete (success)</span></div>
            </div>
        </div>
        <div class="p-m bg-light border-bottom border-top">
            <span class="font-bold no-margins"> Social talks </span> <br>
            <small> Lorem Ipsum is simply dummy text of the printing simply all dummy text.</small>
            <div class="m-t-md">
                <div class="social-talk">
                    <div class="media social-profile clearfix">
                        <a class="pull-left"> <img src="images/a1.jpg" alt="profile-picture"> </a>
                        <div class="media-body">
                            <span class="font-bold">John Novak</span> <small class="text-muted">21.03.2015</small>
                            <div class="social-content small"> Injected humour, or randomised words which don't look even slightly believable. </div>
                        </div>
                    </div>
                </div>
                <div class="social-talk">
                    <div class="media social-profile clearfix">
                        <a class="pull-left"> <img src="images/a3.jpg" alt="profile-picture"> </a>
                        <div class="media-body">
                            <span class="font-bold">Mark Smith</span> <small class="text-muted">14.04.2015</small>
                            <div class="social-content"> Many desktop publishing packages and web page editors. </div>
                        </div>
                    </div>
                </div>
                <div class="social-talk">
                    <div class="media social-profile clearfix">
                        <a class="pull-left"> <img src="images/a4.jpg" alt="profile-picture"> </a>
                        <div class="media-body">
                            <span class="font-bold">Marica Morgan</span> <small class="text-muted">21.03.2015</small>
                            <div class="social-content"> There are many variations of passages of Lorem Ipsum available, but the majority have </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="p-m">
            <span class="font-bold no-margins"> Sales in last week </span>
            <div class="m-t-xs">
                <div class="row">
                    <div class="col-xs-6">
                        <small>Today</small>
                        <h4 class="m-t-xs">$170,20 <i class="fa fa-level-up text-success"></i></h4>
                    </div>
                    <div class="col-xs-6">
                        <small>Last week</small>
                        <h4 class="m-t-xs">$580,90 <i class="fa fa-level-up text-success"></i></h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-6">
                        <small>Today</small>
                        <h4 class="m-t-xs">$620,20 <i class="fa fa-level-up text-success"></i></h4>
                    </div>
                    <div class="col-xs-6">
                        <small>Last week</small>
                        <h4 class="m-t-xs">$140,70 <i class="fa fa-level-up text-success"></i></h4>
                    </div>
                </div>
            </div>
            <small>
                Lorem Ipsum is simply dummy text of the printing simply all dummy text.
                Many desktop publishing packages and web page editors.
            </small>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryCustom")
    <script>
        $(document).ready(function() {
            $('.datepicker').datepicker();
        })
    </script>
}